### ISSUE TITLE
关于 iptables -m string hex

### ISSUE THREAD

**Issue by leenchan** [lifetyper/FreeRouter_V2#10]
在我的路由器上( TP843N / 750mhz 64M )测试过
iptables -m string hex 正确域名解析
但是在数据量大的时候 会拖慢机器 或者 网速
例子：迅雷下载 高速下载可以去到10M/s 左右，
但是由于iptables -m string hex , 下载速度 最多去到 3M/s ~ 4M/s 的速度
有条件的测试一下
看是不是 个例.

**Comment by lifetyper** [comment]
现在已经不用iptables过滤了，而且在用iptables过滤的时候我也没碰到这种问题，所以先关闭了。
