### ISSUE TITLE
查看 iptables 列表的时候，发现里面有三条是乱码呢？

### ISSUE THREAD

**Issue by p0we7** [lifetyper/FreeRouter_V2#11]
如下 ， 
Openwrt trunk 与 Attitude Adjustment 都是这样子。

![qq 20140824181535](https://cloud.githubusercontent.com/assets/8407573/4023157/6cb53ce4-2b79-11e4-9c3d-3e16ec5cb349.jpg)

```
![pic iptables](http://i.imgur.com/S4FoXZx.jpg)
```

**Comment by lifetyper** [comment]
其实我也不知道这是为什么，只是好像没影响工作，而且现在也不用iptables过滤了。依然感谢反馈。

**Comment by p0we7** [comment]
现在有什么方法好啊？ 你的方法用了2个月又被ban掉，又要回到最初的shadowsocks 方法
