### ISSUE TITLE
登录 google 账户后 google 无法打开的问题

### ISSUE THREAD

**Issue by imtxc** [lifetyper/FreeRouter_V2#19]
不登录 google 帐号时，使用 google 搜索没有问题，登录 gmail 等 google 账户之后，就无法正常使用 google 搜索了，是漏掉了哪一个跟账户相关的 google 的域名么？

**Comment by lifetyper** [comment]
我没遇到过这类情况，猜测是你的VPN有问题，这次也更新了小部分Google的域名到列表，但应该和这个问题没有关系，我觉得google的域名列表已经很完全了。

**Comment by imtxc** [comment]
VPN 应该没有问题，是用全局代理或者在 openwrt 上把 vpn 设置成默认路由也正常。
traceroute google.com 也正常

**Comment by lifetyper** [comment]
你所说的无法使用Google搜索的表现是什么呢，因为Google搜索页面本身涉及到的域名很少，我想不出哪里会出问题。

**Comment by imtxc** [comment]
就是在浏览器中无法打开 google.com， 加载非常慢， 但是退出登录 google 账户之后就是正常的.

**Comment by lifetyper** [comment]
建议按最新的commit更新一下DNS策略，现在是默认要翻墙的域名都通过VPN访问国外DNS来解析，我看了一下，涉及的域名应该全部都在列表里了。
