### ISSUE TITLE
如何设置使DNS8.8.8.8直接通过VPN？

### ISSUE THREAD

**Issue by lex1973** [lifetyper/FreeRouter_V2#21]
请问，“route add -host 8.8.8.8 dev pptp -VPN”这条指令是要放在哪个文件或位置才能生效？我这边G+和YOUTUBE都不正常。

**Comment by tedaz** [comment]
不需要脚本。直接在网页界面添加一个静态路由即可：接口选vpn，ip填写8.8.8.8，掩码等其他一律保留空白，保存并应用就可以了。

**Comment by lex1973** [comment]
Thanks！

在 15/1/6，tedaz<notifications@github.com> 写道：
> 不需要脚本。直接在网页界面添加一个静态路由即可：接口选vpn，ip填写8.8.8.8，掩码等其他一律保留空白，保存并应用就可以了。
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/lifetyper/FreeRouter_V2/issues/21#issuecomment-68874192


-- 
庄力13502988455

**Comment by lifetyper** [comment]
新的更新是放在/etc/ppp/ip-up.d/vpnup.sh里面，每次VPN连上的时候就执行这条命令。
