### ISSUE TITLE
新污染ip

### ISSUE THREAD

**Issue by benqiu** [lifetyper/FreeRouter_V2#22]
gfw升级，污染ip库需要升级，谢谢。

**Comment by tedaz** [comment]
现在的污染已经是随机模式了，升级污染ip库已经不管用了。需要按照教程，更改为“白名单”模式——dns仅保留8.8.8.8并且设置静态路由使其通过vpn。

**Comment by benqiu** [comment]
能说的详细点吗？

**Comment by yangyay** [comment]
先说明，我是菜鸟。
我是这样做的：
1.在网页界面添加一个静态路由：接口选vpn，ip填写8.8.8.8，掩码等其他一律保留空白，保存并应用。
2.把etc/dnsmasq.d/gfw.conf中所有的域名全部添加到etc/dnsmasq.d/server.conf。（格式为：server=/google.com/8.8.8.8）
3.把etc/dnsmasq.d/server.conf中的Open DNS，Nortorn DNS，Comodo DNS，DNS Advantage，Verizon DNS，NTT DNS的sever都注释掉。
4.重启路由器。
PS: etc/firewall.user中的iptables过滤污染ip的指令应该可以注释掉了。
现在能访问youtube和看视频了。

**Comment by lifetyper** [comment]
这种随机IP用防火墙规则是很难过滤的，目前最好的办法就是通过VPN通道使用国外DNS，或者使用一些没有倍污染的国内小众DNS。

**Comment by benqiu** [comment]
期待 lifetyper 给个最终版本 最近可闹心了 
我是小白 不是程序员 回去按照yangyay的方法 谢谢 晚上回去试试

**Comment by yysquare** [comment]
@lifetyper 让DNS走VPN的命令是这么写吗：ip route add 8.8.8.8 dev pptp-VPN
我这么写到vpnup.sh后，会导致vpnup.sh执行失败

谢谢！

**Comment by benqiu** [comment]
照做了，其他网站没啥问题，但是youtube无法查看视频是咋回事儿。

**Comment by lex1973** [comment]
我让8.8.8.8走VPN，然后etc/dnsmasq.d/server.conf其他DNS全部删除只留下8.8.8.8，再把所有国内域名指定走114.114.114.114（列表可在https://github.com/felixonmars/dnsmasq-china-list/blob/master/accelerated-domains.china.conf下载）。
目前基本所有被墙网站都正常，google系列也大体不错，特别是youtube非常流畅，就是G+图片显示很慢，也是很奇怪。
可能各地网络情况和各人所用的VPN质量还是有些不同吧～～

**Comment by lex1973** [comment]
我让8.8.8.8走VPN，然后etc/dnsmasq.d/server.conf其他DNS全部删除只留下8.8.8.8，再把所有国内域名指定走114.114.114.114（列表用了https://github.com/felixonmars/dnsmasq-china-list/blob/master/accelerated-domains.china.conf）。
目前基本所有被墙网站都正常，google系列也大体不错，特别是youtube非常流畅，就是G+图片显示很慢，也是很奇怪。
可能各地网络情况和各人所用的VPN质量还是有些不同吧～～

**Comment by lex1973** [comment]
我让8.8.8.8走VPN，然后etc/dnsmasq.d/server.conf其他DNS全部删除只留下8.8.8.8，再把所有国内域名指定走114.114.114.114，列表https://github.com/felixonmars/dnsmasq-china-list/blob/master/accelerated-domains.china.conf   。
目前基本所有被墙网站都正常，google系列也大体不错，特别是youtube非常流畅，就是G+图片显示很慢，也是很奇怪。
可能各地网络情况和各人所用的VPN质量还是有些不同吧～～

**Comment by lifetyper** [comment]
已更新策略，应该已经解决，先关闭这个issue，还有问题请重开。
