### ISSUE TITLE
出现“NET::ERR_CERT_COMMON_NAME_INVALID”

### ISSUE THREAD

**Issue by cheeriofly** [lifetyper/FreeRouter_V2#23]
您好，
按照教程在WNDR3800上搭建FreeRouter_V2，之前工作正常，最近在访问需要翻墙的网址时（如https://docs.google.com ），会出现证书错误的问题，不确定是设置问题，还是VPN问题（已经换了两个不同的VPN，结果一样）。

![0926021](https://cloud.githubusercontent.com/assets/7981138/5770211/1c3747d4-9d62-11e4-8f85-a513a6fa21d0.jpg)

**Comment by cheeriofly** [comment]
另外，直接使用相同的VPN在电脑上翻墙，不会有这个问题。

**Comment by cheeriofly** [comment]
看起来像是DNS被污染的结果。当强制仅使用DNS、且DNS位于VPN之后时，就正常了。

在这个过程中：
1. 客户端发起访问 Twitter.com 的请求,同时发出 DNS 解析请求,请求送达路由器 
2. 路由器上的 Dnsmasq 向所有 DNS 服务器发起解析请求
3. GFW抢先返回虚假解析结果,被iptables防火墙拦截

臆测是“虚假解析结果”发生了变化，进而没有被iptables拦截，所以返回了错误的DNS解析结果。管理员可看看是不是这个原因。

**Comment by qiumaoyuan** [comment]
我也遇到同样的问题，最近几天才出现。也是在电脑上用 VPN 没问题，但是在路由里用就这样。

**Comment by cheeriofly** [comment]
恩，我也是最近几天才碰到这个问题的。看来路由器翻墙机制还得随着墙的升级而升级。

**Comment by qiumaoyuan** [comment]
@cheeriofly 我用 firebug 看了一下，刚向 dropbox 发送了一个请求，请求的 ip 和端口是 46.19.141.37:443，我试着在浏览器里直接访问这个 ip，显示“连接被重置”。也就是说，不知道为什么这个 ip 似乎并没有被加到翻墙名单中来。我在 dnsmasq.d/gfw.conf 里是加了 dropbox.com 这个域名的。

**Comment by qiumaoyuan** [comment]
再做了个试验证实了一下。我在自己的电脑上 ping 46.19.141.37，同时在路由器里 tcpdump -i pptp-fuckgfw dst 46.19.141.37（pptp-fuckgfw 是 vpn 接口名），是看不到任何输出的。但我在电脑上 ping 173.194.72.84，同时在路由里 tcpdump -i pptp-fuckgfw dst 173.194.72.84 能看到输出。也就是说前面那个 ip 没有走 VPN。

**Comment by cheeriofly** [comment]
那看起来是IPSet没正确干活？再深我也不懂了~

**Comment by qiumaoyuan** [comment]
其实我觉得云梯提供的那种路由表，先让所有流量默认走 VPN 通道，把用一个表把绝大多数国内网站的 IP 导回来，这种方案挺好的，免掉了更多维护列表的工作。即便偶尔有几个国内网站漏写了，也能通过 VPN 访问到，只是速度慢一些而已。

**Comment by tony7day** [comment]
遇到了同样的问题。

**Comment by lifetyper** [comment]
很多问题都是新DNS污染造成的，这个应该也是，参考tony的文章或者本项目的最新更新即可。

**Comment by qiumaoyuan** [comment]
@tony7day 多谢 :D 不过我用你的办法试了一下，问题好像仍然存在。最后在 /etc/ppp/ip-up/vpnup.sh 里加了两行解决问题：

VPN_GW=$(ip route show|grep 'pptp'| sed -e 's#^\([^ ]*\) .*#\1#g')
ip route add 8.8.8.8 via $VPN_GW dev $VPN_DEV

就是让 8.8.8.8 的访问走 VPN，需要的话还可以把 8.8.4.4 加上。
