### ISSUE TITLE
好像 cloudfront.net 的资源大多数情况下一直无法载入

### ISSUE THREAD

**Issue by qiumaoyuan** [lifetyper/FreeRouter_V2#26]
大家是如何解决的？原因是什么？

trello.com, apidock.com, name.com 这些经常上的网站都用 cloudfront.net 的资源，老是无法正常打开。

**Comment by lifetyper** [comment]
这类问题你们都应该去问VPN服务商，从来也没有哪个VPN是可以打开全世界网络的。

**Comment by qiumaoyuan** [comment]
问题是我直接在电脑上连接 VPN 访问这些网站完全正常。
